# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('adress', models.CharField(max_length=100, verbose_name='Endere\xe7o')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('mobile', models.CharField(max_length=20, verbose_name='Celular')),
                ('about', models.TextField(max_length=255, verbose_name='Sobre')),
                ('data_nascimento', models.CharField(default='01 Janeiro 2017', max_length=255, verbose_name='Data Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('conhecimentos', models.TextField(max_length=255, verbose_name='Conhecimentos')),
                ('github', models.CharField(default='https://github.com/rewthnunes', max_length=100, verbose_name='GitHub')),
                ('current_position', models.CharField(max_length=100, verbose_name='Desenvolvedor')),
                ('empresa', models.CharField(max_length=100, verbose_name='IFSP-CAMPINAS')),
            ],
        ),
    ]
