# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_auto_20171022_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='current_position',
            field=models.CharField(default='Desenvolvedor', max_length=100, verbose_name='Cargo Atual'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='empresa',
            field=models.CharField(default='IFSP-CAMPINAS', max_length=100, verbose_name='Empresa'),
        ),
    ]
