# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_auto_20171030_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PesquisaSaoPaulo',
        ),
        migrations.AlterModelOptions(
            name='dadospessoais',
            options={'verbose_name': 'Dados Pessoais', 'verbose_name_plural': 'Dados Pessoais'},
        ),
    ]
