# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_dadossaopaulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadossaopaulo',
            options={'verbose_name': 'Dados S\xe3o Paulo', 'verbose_name_plural': 'Dados S\xe3o Paulo'},
        ),
        migrations.AddField(
            model_name='dadossaopaulo',
            name='D2',
            field=models.CharField(default='0', max_length=1, verbose_name='D2 - Comunicabilidade'),
        ),
        migrations.AddField(
            model_name='dadossaopaulo',
            name='D3',
            field=models.CharField(default='0', max_length=1, verbose_name='D3 - Disponibilidade'),
        ),
        migrations.AddField(
            model_name='dadossaopaulo',
            name='D4',
            field=models.CharField(default='0', max_length=1, verbose_name='D4 - Multiplicidade Acesso'),
        ),
        migrations.AddField(
            model_name='dadossaopaulo',
            name='D5',
            field=models.CharField(default='0', max_length=1, verbose_name='D5 - Acessibilidade'),
        ),
        migrations.AddField(
            model_name='dadossaopaulo',
            name='D6',
            field=models.CharField(default='0', max_length=1, verbose_name='D6 - Confiabilidade'),
        ),
        migrations.AddField(
            model_name='dadossaopaulo',
            name='D7',
            field=models.CharField(default='0', max_length=1, verbose_name='D7 - Usabilidade'),
        ),
        migrations.AddField(
            model_name='dadossaopaulo',
            name='D8',
            field=models.CharField(default='0', max_length=1, verbose_name='D8 - Transpar\xeancia'),
        ),
        migrations.AddField(
            model_name='dadossaopaulo',
            name='D9',
            field=models.CharField(default='0', max_length=1, verbose_name='D9 - Presta\xe7\xe3o de Contas'),
        ),
        migrations.AlterField(
            model_name='dadossaopaulo',
            name='D1',
            field=models.CharField(default='0', max_length=1, verbose_name='D1 - Maturidade'),
        ),
    ]
