# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_auto_20171030_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosPessoais',
        ),
    ]
