# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0011_auto_20171031_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DadosPessoais',
            new_name='SaoPaulo',
        ),
        migrations.AlterModelOptions(
            name='saopaulo',
            options={'verbose_name': 'S\xe3o Paulo', 'verbose_name_plural': 'S\xe3o Paulo'},
        ),
    ]
