# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0013_auto_20171031_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saopaulo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
