# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0015_auto_20171031_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='populacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Habitantes')),
                ('SaoPaulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.SaoPaulo')),
            ],
        ),
    ]
