# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0016_populacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='populacao',
            options={'verbose_name': 'Popula\xe7\xe3o', 'verbose_name_plural': 'Popula\xe7\xe3o'},
        ),
    ]
