# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0017_auto_20171126_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saopaulo',
            options={'verbose_name': 'Local de Pesquisa', 'verbose_name_plural': 'Local de Pesquisa'},
        ),
    ]
